package com.portafolio2017.rest.entity;
// Generated 29-10-2017 16:52:28 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CargoModel generated by hbm2java
 */
@Entity
@Table(name = "cargo")
public class Cargo implements java.io.Serializable {

	@Id
	@Column(name = "id_cargo", unique = true, nullable = false, precision = 8, scale = 0)
	private int idCargo;
	
	@Column(name = "nombre_cargo", nullable = false, length = 50)
	private String nombreCargo;
	
	@Column(name = "salario", nullable = false, precision = 10, scale = 0)
	private long salario;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "cargo")
	private Set<Funcionario> funcionarios = new HashSet<Funcionario>();
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "cargo")
	private Set<HistorialCargo> historialCargos = new HashSet<HistorialCargo>();

	public Cargo() {
	}

	public Cargo(int idCargo, String nombreCargo, long salario) {
		this.idCargo = idCargo;
		this.nombreCargo = nombreCargo;
		this.salario = salario;
	}

	

	
	public Cargo(int idCargo, String nombreCargo, long salario, Set<Funcionario> funcionarios,
			Set<HistorialCargo> historialCargos) {
		super();
		this.idCargo = idCargo;
		this.nombreCargo = nombreCargo;
		this.salario = salario;
		this.funcionarios = funcionarios;
		this.historialCargos = historialCargos;
	}

	public int getIdCargo() {
		return this.idCargo;
	}

	public void setIdCargo(int idCargo) {
		this.idCargo = idCargo;
	}

	
	public String getNombreCargo() {
		return this.nombreCargo;
	}

	public void setNombreCargo(String nombreCargo) {
		this.nombreCargo = nombreCargo;
	}

	
	public long getSalario() {
		return this.salario;
	}

	public void setSalario(long salario) {
		this.salario = salario;
	}

	public Set<Funcionario> getFuncionarios() {
		return funcionarios;
	}

	public void setFuncionarios(Set<Funcionario> funcionarios) {
		this.funcionarios = funcionarios;
	}

	public Set<HistorialCargo> getHistorialCargos() {
		return historialCargos;
	}

	public void setHistorialCargos(Set<HistorialCargo> historialCargos) {
		this.historialCargos = historialCargos;
	}


}
