package com.portafolio2017.rest.entity;
// Generated 29-10-2017 16:52:28 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DepartamentoModel generated by hbm2java
 */
@Entity
@Table(name = "departamento")
public class Departamento implements java.io.Serializable {

	@Id
	@Column(name = "id_depto", unique = true, nullable = false, precision = 8, scale = 0)
	private int idDepto;
	
	@Column(name = "nombre_depto", nullable = false)
	private String nombreDepto;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "departamento")
	private Set<Funcionario> funcionarios = new HashSet<Funcionario>();

	public Departamento() {
	}

	public Departamento(int idDepto, String nombreDepto) {
		this.idDepto = idDepto;
		this.nombreDepto = nombreDepto;
	}


	
	public Departamento(int idDepto, String nombreDepto, Set<Funcionario> funcionarios) {
		super();
		this.idDepto = idDepto;
		this.nombreDepto = nombreDepto;
		this.funcionarios = funcionarios;
	}

	public int getIdDepto() {
		return this.idDepto;
	}

	public void setIdDepto(int idDepto) {
		this.idDepto = idDepto;
	}

	
	public String getNombreDepto() {
		return this.nombreDepto;
	}

	public void setNombreDepto(String nombreDepto) {
		this.nombreDepto = nombreDepto;
	}

	public Set<Funcionario> getFuncionarios() {
		return funcionarios;
	}

	public void setFuncionarios(Set<Funcionario> funcionarios) {
		this.funcionarios = funcionarios;
	}

	


}
