package com.portafolio2017.rest.entity;
// Generated 29-10-2017 16:52:28 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistorialCargoModel generated by hbm2java
 */
@Entity
@Table(name = "historial_cargo")
public class HistorialCargo implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "id_historial", unique = true, nullable = false)
	private int id_historial;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 7)
	private Date fechaInicio;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cargo_id_cargo", nullable = false)
	private Cargo cargo;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_termino", length = 7)
	private Date fechaTermino;

	public HistorialCargo() {
	}


	public HistorialCargo(int id_historial, Cargo cargo) {
		super();
		this.id_historial = id_historial;
		this.cargo = cargo;
	}


	
	public HistorialCargo(int id_historial, Date fechaInicio, Cargo cargo, Date fechaTermino) {
		super();
		this.id_historial = id_historial;
		this.fechaInicio = fechaInicio;
		this.cargo = cargo;
		this.fechaTermino = fechaTermino;
	}

	

	public int getId_historial() {
		return id_historial;
	}


	public void setId_historial(int id_historial) {
		this.id_historial = id_historial;
	}


	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}


	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	
	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

}
