#Puerto del servidor
server:
  port: 8082
  contextPath: /api-rest
  error:
    whitelabel:
      enabled: false
  
#Directorio del banner de Springboot tras arrancar el servidor

spring:
  datasource: 
    url: jdbc:mysql://myorion.ct8hgadd3koi.sa-east-1.rds.amazonaws.com:3306/orionFunDB?useSSL=false  # JDBC url of the database. jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: crisOrion                                             # Login user of the database.           maty
    password: 123456123                                         # Login password of the database.
  jpa:
    show-sql: true                                              # Enable logging of SQL statements.
    hibernate:
      ddl-auto: update                                          # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
      naming:
        strategy: org.hibernate.cfg.improvedNamingStrategy      # Hibernate 4 naming strategy fully qualified name. Not supported with Hibernate 5.
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect              # Additional native properties to set on the JPA provider.
  
  thymeleaf:
    cache: false                                                # No admite cache en Thyleaf